### PR TITLE
Apply BTCPay design basics

### PR DESCRIPTION
**Pull request by dennisreimann**
This is a draft, laying the basics for #8. 

Using the Configurator as an integration point, I'm also fleshing out the basics of the design system styles: My plan for the first step is to keep the shared styles as minimalistic as possible. Think it'd make sense to ship a custom bootstrap.css (taken from the BTCPay backend), so that we can also reuse it like here in the Configurator. This way we'd not reinvent the components, but basically come up with our own way of customizing bootstrap.

Right now the shared styles are mostly color related and otherwise build on what's provided by Bootstrap. 

Regarding the themes: Light is the default, but we respect the system settings and switch to dark via CSS if that's supported and wanted. In addition to that there's also the ability to explicitely set the theme to light or dark. This way we have the best of all worlds.

light

dark

### CODE REVIEW

**Comment by Eskyee** [comment]
lovin the BTCPay Configurator .... excellent job!

**Comment by Kukks** [comment]
Some screen grabs: 
firefox_G6vxnEWFLm
firefox_k4cudty87V
firefox_ZIS7LVEaEA
firefox_G8xcF1dF2i
firefox_WfJeZwuQ6r
firefox_X6OE9IyoGU
firefox_2JBivceqQQ
firefox_WlFMrC2vbI
firefox_ipujc3NYUA
firefox_7jB5VpOUWq

**Comment by Kukks** [comment]
The only broken thing I noticed is in Step 3 Chain. It does not show that Bitcoin is selected and you cannot toggle it by clicking.
image

**Comment by Kukks** [comment]
Light mode in Step4 does not play very well with some of the images
image

**Comment by Kukks** [comment]
@pavlenex  now is the time to pour in your feedback :P

**Comment by Eskyee** [comment]
> The only broken thing I noticed is in Step 3 Chain. It does not show that Bitcoin is selected and you cannot toggle it by clicking.
> image

I could see bitcoin toggle on my raspberrypi last built version, I had kukks,

excellent stuff

**Comment by Eskyee** [comment]
Screenshot 2020-04-25 at 10 08 17

**Comment by Eskyee** [comment]
excited to see the new themes .. awesome job

**Comment by dennisreimann** [comment]
Fixes and changes applied – thanks for your feedback!

nodes-light

lightning-light

**Comment by pavlenex** [comment]
Now I love the configurator even more. Great work on the color-scheme Dennis. I don't have much to say about the UI here since this PR tackles the theme, but I noticed just one thing:

**Comment by dennisreimann** [comment]
Fixed :)

destination

**Comment by dennisreimann** [comment]
@Kukks Can't wait for the merge!

doit

**Comment by Eskyee** [comment]
Dope 🔥BTCPAY Configurable App 😎 Can’t wait for the drop !! 😋 all gassed up 😂

**Comment by dennisreimann** [comment]
Added the [theme switch](https://design.btcpayserver.org/components/theme-switch/) 👍

Theme Switch

**Pull request merged**
